"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
const names:any={FREE:"Gratuit / Essai",BUSINESS:"Basic",ENTERPRISE:"Avancé"};
const prices:any={FREE:0,BUSINESS:7500,ENTERPRISE:10000};
export default function SubscriptionPage(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[notice,setNotice]=useState("");
 async function load(){try{const d=await fetch('/api/me').then(r=>r.json());const cid=d?.user?.companies?.[0]?.id;if(!cid){setError("Aucune entreprise trouvée.");return}const r=await fetch(`/api/companies/${cid}/subscription`);const x=await r.json();if(!r.ok)throw new Error(x.error||"Impossible de charger l'abonnement.");setData({...x,companyId:cid});}catch(e:any){setError(e.message||"Impossible de charger l'abonnement.")}}
 useEffect(()=>{load()},[]);
 async function renew(){if(!data?.companyId)return;setBusy(true);setNotice("");try{const r=await fetch(`/api/companies/${data.companyId}/subscription`,{method:'PUT'});const x=await r.json();if(!r.ok)throw new Error(x.error||"Demande impossible");setNotice(x.alreadyPending?"Une demande de renouvellement est déjà en attente.":"Demande envoyée. Le Superadmin validera votre paiement en espèces.");}catch(e:any){setNotice(e.message||"Erreur")}finally{setBusy(false)}}
 const s=data?.subscription; const end=s?.currentPeriodEnd?new Date(s.currentPeriodEnd):null; const expired=!!end && end.getTime()<Date.now(); const pending=data?.orders?.some?.((o:any)=>o.status==='PENDING');
 return <main style={{maxWidth:1100,margin:'0 auto',padding:'32px 18px 70px'}}>
  <div style={{marginBottom:25}}><div style={{fontSize:12,color:'#2563eb',fontWeight:900,letterSpacing:1}}>MON ESPACE</div><h1 style={{fontSize:'clamp(30px,5vw,44px)',margin:'7px 0'}}>Mon abonnement</h1><p style={{color:'#64748b',margin:0}}>Gérez votre formule et demandez son renouvellement directement depuis BizManager.</p></div>
  {error&&<div role="alert" style={{padding:14,borderRadius:10,background:'#fef2f2',color:'#b91c1c',marginBottom:18}}>{error}</div>}
  {notice&&<div role="status" style={{padding:14,borderRadius:10,background:'#ecfdf5',color:'#047857',marginBottom:18}}>{notice}</div>}
  {s&&<><section className="bm-subscription-hero" style={{background:'white',border:'1px solid #e2e8f0',borderRadius:18,padding:24,boxShadow:'0 8px 30px #0f172a0a',display:'grid',gridTemplateColumns:'1fr auto',gap:20,alignItems:'center'}}><div><div style={{fontSize:13,color:'#64748b'}}>FORMULE ACTUELLE</div><h2 style={{fontSize:30,margin:'6px 0'}}>{names[s.plan]||s.plan}</h2><p style={{margin:'5px 0',color:'#64748b'}}>{prices[s.plan].toLocaleString('fr-FR')} FCFA / mois</p><div style={{marginTop:14,display:'flex',gap:8,flexWrap:'wrap'}}><span style={{padding:'7px 10px',borderRadius:999,background:expired?'#fef2f2':s.status==='ACTIVE'?'#ecfdf5':'#fff7ed',color:expired?'#b91c1c':s.status==='ACTIVE'?'#047857':'#c2410c',fontWeight:800,fontSize:12}}>{expired?'EXPIRÉ':s.status}</span>{end&&<span style={{padding:'7px 10px',borderRadius:999,background:'#f1f5f9',color:'#475569',fontSize:12}}>Fin : {end.toLocaleDateString('fr-FR')}</span>}</div></div><div style={{background:'#eff6ff',color:'#1e40af',padding:18,borderRadius:14,maxWidth:350}}><strong>Renouvellement en espèces</strong><p style={{margin:'7px 0 12px',lineHeight:1.5,fontSize:14}}>Envoyez une demande. Le Superadmin enregistrera le paiement et prolongera votre abonnement.</p>{s.plan!=='FREE'&&<button onClick={renew} disabled={busy||pending} style={{width:'100%',padding:11,border:0,borderRadius:9,background:'#2563eb',color:'white',fontWeight:800,cursor:'pointer'}}>{busy?'Envoi…':pending?'Demande déjà envoyée':'Demander le renouvellement'}</button>}</div></section>
  <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(230px,1fr))',gap:16,marginTop:22}}>{data.featureMatrix?.basic?.map((x:string)=><div key={x} style={{background:'white',padding:18,borderRadius:14,border:'1px solid #e2e8f0'}}>✓ {x}</div>)}{data.featureMatrix?.advanced?.map((x:string)=><div key={x} style={{background:s.plan==='ENTERPRISE'?'white':'#f8fafc',padding:18,borderRadius:14,border:'1px solid #e2e8f0',color:s.plan==='ENTERPRISE'?'#0f172a':'#94a3b8'}}>{s.plan==='ENTERPRISE'?'✓':'🔒'} {x}</div>)}</div>
  <div style={{marginTop:24,textAlign:'center'}}><Link href="/pricing" style={{color:'#2563eb',fontWeight:800,textDecoration:'none'}}>Voir les formules et tarifs →</Link></div></>}
 </main>
}
