"use client";
import {useState} from "react";
import Link from "next/link";
export default function Register(){
 const [f,setF]=useState({firstName:"",lastName:"",email:"",password:"",companyName:""}); const [m,setM]=useState(""); const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setM("");try{const r=await fetch("/api/auth/register",{method:"POST",headers:{"content-type":"application/json"},credentials:"include",body:JSON.stringify(f)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Création impossible");window.location.replace("/dashboard")}catch(e:any){setM(e.message||"Une erreur est survenue");setBusy(false)}}
 const set=(k:string,v:string)=>setF(x=>({...x,[k]:v}));
 return <main className="bm-register" style={{minHeight:"100vh",display:"grid",gridTemplateColumns:"1fr 500px",fontFamily:"Arial,sans-serif",background:"#f8fafc"}}><section style={{padding:60,background:"linear-gradient(135deg,#0f172a,#1d4ed8)",color:"white",display:"flex",flexDirection:"column",justifyContent:"center"}}><Link href="/" style={{color:"white",textDecoration:"none",fontSize:25,fontWeight:800}}>♥ BizManager</Link><h1 style={{fontSize:52,maxWidth:650,lineHeight:1.05}}>Commencez à gérer votre entreprise.</h1><p style={{fontSize:19,color:"#dbeafe",maxWidth:600,lineHeight:1.6}}>Créez votre espace gratuitement et commencez avec votre propre entreprise et votre rôle Owner.</p><div style={{marginTop:24,color:"#bfdbfe"}}>✓ Ventes et caisse<br/>✓ Stock et achats<br/>✓ Clients et fournisseurs<br/>✓ Trésorerie et rapports</div></section><section style={{display:"flex",alignItems:"center",padding:30}}><form onSubmit={submit} style={{width:"100%",background:"white",padding:32,borderRadius:20,boxShadow:"0 15px 50px #00000010"}}><Link href="/" style={{textDecoration:"none",color:"#64748b"}}>← Accueil</Link><h2 style={{fontSize:30,marginBottom:6}}>Créer mon compte</h2><p style={{color:"#64748b",marginTop:0}}>Votre compte devient automatiquement Owner de votre entreprise.</p><div className="bm-register-name-grid" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:14}}><label>Prénom<input required value={f.firstName} onChange={e=>set("firstName",e.target.value)} style={input}/></label><label>Nom<input required value={f.lastName} onChange={e=>set("lastName",e.target.value)} style={input}/></label></div><label style={block}>E-mail<input required type="email" autoComplete="email" value={f.email} onChange={e=>set("email",e.target.value)} style={input}/></label><label style={block}>Mot de passe<input required type="password" minLength={8} autoComplete="new-password" value={f.password} onChange={e=>set("password",e.target.value)} style={input}/></label><label style={block}>Nom de l'entreprise<input required value={f.companyName} onChange={e=>set("companyName",e.target.value)} style={input}/></label>{m&&<div role="alert" style={{marginTop:16,padding:12,borderRadius:9,background:"#fef2f2",color:"#b91c1c",fontSize:14}}>{m}</div>}<button disabled={busy} style={button}>{busy?"Création…":"Créer mon espace"}</button><p style={{fontSize:13,color:"#64748b",textAlign:"center"}}>Déjà un compte ? <Link href="/login">Se connecter</Link></p></form></section></main>
}
const block:any={display:"block",marginTop:16};const input:any={display:"block",width:"100%",boxSizing:"border-box",padding:13,marginTop:7,border:"1px solid #cbd5e1",borderRadius:9,fontSize:15};const button:any={width:"100%",marginTop:22,padding:14,border:0,borderRadius:10,background:"#111827",color:"white",fontWeight:800,fontSize:16,cursor:"pointer"};
