"use client";
import {useEffect,useState} from "react";
const card:any={background:"white",border:"1px solid #e2e8f0",borderRadius:16,padding:22,boxShadow:"0 5px 20px #0f172a0a"};
const input:any={width:"100%",boxSizing:"border-box",padding:"11px 12px",border:"1px solid #cbd5e1",borderRadius:9,marginTop:6};
export default function SettingsClient({user}:{user:{email:string,firstName:string,lastName:string,companies:{name:string,role:string}[]}}){
 const [currentPassword,setCurrentPassword]=useState("");const [newPassword,setNewPassword]=useState("");const [confirm,setConfirm]=useState("");const [msg,setMsg]=useState("");const [sessions,setSessions]=useState<any[]>([]);const [busy,setBusy]=useState(false);
 async function loadSessions(){const r=await fetch("/api/account/sessions");const d=await r.json();if(r.ok)setSessions(d.sessions||[])}
 useEffect(()=>{loadSessions()},[]);
 async function changePassword(e:React.FormEvent){e.preventDefault();setMsg("");if(newPassword!==confirm){setMsg("Les deux nouveaux mots de passe ne correspondent pas.");return}setBusy(true);try{const r=await fetch("/api/account/password",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Erreur");setCurrentPassword("");setNewPassword("");setConfirm("");setMsg("Mot de passe modifié avec succès.");await loadSessions()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 async function revoke(){setBusy(true);setMsg("");try{const r=await fetch("/api/account/sessions",{method:"DELETE"});const d=await r.json();if(!r.ok)throw new Error(d.error);setMsg("Les autres sessions ont été fermées.");await loadSessions()}catch(e:any){setMsg(e.message)}finally{setBusy(false)}}
 return <main style={{maxWidth:1050,margin:"0 auto",padding:"30px 20px 70px"}}><div style={{marginBottom:24}}><div style={{fontSize:12,color:"#2563eb",fontWeight:800,textTransform:"uppercase",letterSpacing:1}}>Paramètres</div><h1 style={{fontSize:32,margin:"7px 0"}}>Mon compte & sécurité</h1><p style={{color:"#64748b",margin:0}}>Gérez vos informations de compte et la sécurité de vos accès BizManager.</p></div>{msg&&<div style={{padding:13,marginBottom:16,borderRadius:10,background:msg.includes("succès")||msg.includes("fermées")?"#dcfce7":"#fff7ed",color:msg.includes("succès")||msg.includes("fermées")?"#166534":"#9a3412"}}>{msg}</div>}<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:18}}><section style={card}><h2 style={{marginTop:0}}>Profil</h2><p><strong>{user.firstName} {user.lastName}</strong></p><p style={{color:"#64748b"}}>{user.email}</p><h3>Entreprises</h3>{user.companies.map(c=><div key={c.name} style={{display:"flex",justifyContent:"space-between",padding:"10px 0",borderTop:"1px solid #e2e8f0"}}><span>{c.name}</span><strong>{c.role}</strong></div>)}</section><form onSubmit={changePassword} style={card}><h2 style={{marginTop:0}}>Changer le mot de passe</h2><label>Mot de passe actuel<input type="password" required value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} style={input}/></label><br/><label>Nouveau mot de passe<input type="password" required minLength={8} value={newPassword} onChange={e=>setNewPassword(e.target.value)} style={input}/></label><br/><label>Confirmer<input type="password" required minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} style={input}/></label><button disabled={busy} style={{marginTop:16,width:"100%",padding:12,border:0,borderRadius:9,background:"#2563eb",color:"white",fontWeight:800,cursor:"pointer"}}>{busy?"Traitement…":"Modifier le mot de passe"}</button></form><section style={{...card,gridColumn:"1/-1"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap"}}><div><h2 style={{margin:"0 0 5px"}}>Sessions actives</h2><p style={{margin:0,color:"#64748b"}}>{sessions.length} session(s) active(s)</p></div><button onClick={revoke} disabled={busy||sessions.length<2} style={{padding:"10px 14px",borderRadius:9,border:"1px solid #fecaca",background:"#fff1f2",color:"#be123c",fontWeight:800,cursor:"pointer"}}>Fermer les autres sessions</button></div><div style={{marginTop:16}}>{sessions.map((s,i)=><div key={s.id} style={{padding:"12px 0",borderTop:"1px solid #e2e8f0",display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><span>{i===0?"Session la plus récente":"Session active"}</span><span style={{color:"#64748b",fontSize:13}}>Dernière activité : {new Date(s.lastSeenAt).toLocaleString("fr-FR")}</span></div>)}</div></section></div></main>}
